### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by adel-tahir** [adel-tahir/hermes#2]

**Comment by sean-madhavan** [comment]
@adel-tahir I am not online in the afternoon. are you online on Wed morning?

**Comment by adel-tahir** [comment]
@sean-madhavan Ok, I'll be online.

**Comment by adel-tahir** [comment]
contact here @sean-madhavan

**Comment by sean-madhavan** [comment]
@adel-tahir are you around?

**Comment by adel-tahir** [comment]
hey, man, i'm here

**Comment by sean-madhavan** [comment]
I am freelancer chat. can you get there?

**Comment by adel-tahir** [comment]
can u do directly thru pp?

**Comment by sean-madhavan** [comment]
which country?

**Comment by adel-tahir** [comment]
possibly chinese accnt

**Comment by sean-madhavan** [comment]
when is deadline?

**Comment by adel-tahir** [comment]
by the end of this month

**Comment by sean-madhavan** [comment]
five bucks?

**Comment by adel-tahir** [comment]
yea

**Comment by sean-madhavan** [comment]
I will check about that and get back to you by the end of this week. otherwise, I should use freelancer.

**Comment by adel-tahir** [comment]
Hey, you can send thru freelancer.

**Comment by sean-madhavan** [comment]
@adel-tahir are you okay from china paypal?

**Comment by adel-tahir** [comment]
@sean-madhavan Please send me on freelancers.com. That will work perfect.

**Comment by adel-tahir** [comment]
my freelancer account is realmgpro.

**Comment by adel-tahir** [comment]
@sean-madhavan you can contact me on freelancer by "realmgpro"

**Comment by sean-madhavan** [comment]
@adel-tahir Please come to ksch41 for quick chat

**Comment by adel-tahir** [comment]
I am waiting. reply asap.

**Comment by sean-madhavan** [comment]
are you on freelancer now？

**Comment by adel-tahir** [comment]
Hi, Please come to realmgpro in freelance.
I am waiting invitation for project in freelance now.
See you soon.
